project:
  type: website

website:
  title: "Seoyeon's Blog for classes"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/seoyeonc/md
  sidebar:
    style: "docked"
    search: true
    contents: auto
    
format:
  html:
    theme:
        light: Pulse
    css: styles.css
    toc: true
    code-fold: false
    code-line-numbers: false
    code-copy: false
    # fontsize: 0.9em
