project:
  type: website

website:
  title: "Master's Degree"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/seoyeonc/md
  sidebar:
    style: "docked"
    search: true
    contents: auto
    
    format:
      html:
        theme: 
            light: superhero
            dark: darkly
        css: styles.css
        toc: true
        code-fold: false
        code-line-numbers: false
        code-copy: true
        fontsize: 0.9em
